#!/bin/bash

git stash push --staged -m "staged changes only"
git stash push -u -m "non-staged changes only"
git stash pop stash@{1}
npm run lint -- --fix
npm run format
git add .
npm run test
npm run build